# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        avatar_uploads_adapter:
            local:
                location: '%kernel.project_dir%/public/%avatar_uploads%'

    filesystems:
        uploads_avatar:
            adapter: avatar_uploads_adapter
